corpusDir: './corpus/'
testMode: assertion
coverage: true
solcArgs: "--evm-version cancun --optimize-runs 200"
testLimit: 10000
shrinkLimit: 10000
#testMaxGas is a gas limit; does not cause failure, but terminates sequence
testMaxGas: 12500000
#maxGasprice is the maximum gas price
# maxGasprice: 0